import type { NextConfig } from "next";

/**
 * Identifies the build. On Vercel this is the commit SHA; locally it falls back
 * to the start time so a dev restart counts as a new build.
 *
 * Baked into the client bundle AND readable server-side, which is what makes an
 * update check possible: a running client carries the id of the build it was
 * served from, while /api/version reports whatever build is deployed now. If
 * they differ, the app on screen is stale.
 */
const buildId =
  process.env.VERCEL_GIT_COMMIT_SHA?.slice(0, 12) ||
  process.env.BUILD_ID ||
  `dev-${Date.now()}`;

const nextConfig: NextConfig = {
  // Keep server-only native/node packages out of the client + edge bundles.
  serverExternalPackages: [
    "@prisma/client",
    "@prisma/adapter-pg",
    "pg",
    "bcryptjs",
    "nodemailer",
    "web-push",
    "@simplewebauthn/server",
  ],
  env: {
    NEXT_PUBLIC_BUILD_ID: buildId,
    APP_BUILD_ID: buildId,
    // The app name is configurable for emails; the client needs it too, for the
    // "add to Home Screen" copy in lib/push-client.ts.
    NEXT_PUBLIC_APP_NAME: process.env.APP_NAME || "PRO-SYS",
  },
  async headers() {
    return [
      {
        // public/icons/* are generated by scripts/generate-icons.mjs and only change
        // when the app is rebranded, but Next serves everything under public/ with
        // `max-age=0`. The service worker routes them cache-first and then declines to
        // store anything the server hasn't marked immutable — deliberately, because
        // `next dev` serves unhashed chunks under the same rule — so the icons were
        // going through a cache that could never hold them and simply failing offline,
        // where leaving them to the HTTP cache would at least have worked. Saying
        // immutable here is what makes isImmutable() in public/sw.js true.
        source: "/icons/:file*",
        headers: [
          { key: "Cache-Control", value: "public, max-age=31536000, immutable" },
        ],
      },
      {
        // Nothing in this app is meant to be framed, and it holds one household's
        // money and movements. `frame-ancestors` is the modern form; X-Frame-Options
        // is kept for readers that predate it.
        source: "/:path*",
        headers: [
          { key: "Content-Security-Policy", value: "frame-ancestors 'none'" },
          { key: "X-Frame-Options", value: "DENY" },
          { key: "X-Content-Type-Options", value: "nosniff" },
          // Send no referrer off-origin: a reminder URL should not travel to whatever
          // a link in a description points at.
          { key: "Referrer-Policy", value: "strict-origin-when-cross-origin" },
        ],
      },
    ];
  },
};

export default nextConfig;
